import { Player, Match, Prediction, ActivityFeedItem } from './types';

export const INITIAL_PLAYERS: Player[] = [
  {
    id: 'anhquoc',
    name: 'Anh Quốc',
    avatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuB1d8kofoTWsY2b-i2xCczJphsKBr5-X6Ol0iSQLwac4vGm2OZHvpXkEvhoF0WGji6DvS6WB6umBcMuwrXduEqMctu7-fUjZlkXQHJTytSX-bL8YklV65CqfHQYqO8vUXnWjGwH-vYbcYm4OYFGR3jF-sYsu6EmyxBOsrJ_V3gB6Tbiqs17mCJB6sAihEavyGvAwvyxfZgaEr51l06l5u_-LSl6rEJNUoUnzauYRpkhcKOqhGIMJ3SGAq6Maq14IYCKEMFTzMm_RQP1',
    totalPredictionsCount: 40,
    notLoseCount: 30,
    loseHalfCount: 4,
    loseCount: 4,
    loseDoubleCount: 2,
    totalPenaltyVnd: 0, // Rank 1: 0 VND / 0 Penalty points
  },
  {
    id: 'minhhoang',
    name: 'Minh Hoàng',
    avatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBc7OscwVisw0NYcUn_WgJdq8pZXgfmr72aIAibBMmA-g__A4A4wxkPb0MBUtPcnUg2AFF1j9VOiHFBA-Zl6Rhw1A2sjBvMRJgQ065sHS1TtLppl5Kdqk8Lhxfzj6R72z-wEDvhj_ZaUiqINB0eRdut2_PtXlf6eOELVbjelWTqhJYtYyrB-wrcPXkpku1eWGfFW27Mu9SkBH7REy3xPokfh9mrjq3vA8sbLKPNpBl5YHfXpeImu1s8X9Igvh7LFXfud5w0NsaWWSPC',
    totalPredictionsCount: 41,
    notLoseCount: 29,
    loseHalfCount: 5,
    loseCount: 5,
    loseDoubleCount: 2,
    totalPenaltyVnd: 25000, // Rank 2: 2.5 Penalty
  },
  {
    id: 'vanthanh',
    name: 'Văn Thanh',
    avatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuABSF6-xaFzybecLgmq6gy0h4IdDFx--91QpSuEXHOgLEdy7NH0xZYpVSkIYO0rHY-UVpYivn5sh3MBk36May8s1kCkA9ihTXZnw5Vl9YJOeR-ZONZLViH6Vv9k8PN_MwztYcCKr2AXvM9G6B0IM8nPJk4l3fnxLSoDmWe__70Ft8wVH1hhc8VVeoFJSaq-Oq8YUFSGorTmFN8WvRr2er0Z0Aa_1ayd0GrrhqqlZD63qpwKOoUx0OCDVY7r_hvTjmFlPU3J6OqnEZpo',
    totalPredictionsCount: 42,
    notLoseCount: 28,
    loseHalfCount: 4,
    loseCount: 6,
    loseDoubleCount: 4,
    totalPenaltyVnd: 30000, // Rank 3: 3.0 Penalty
  },
  {
    id: 'alex',
    name: 'Alex Tran',
    avatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuC7ZIbfNpjYPQoDxBTHf3g-v8qMwrsxawTBWkOb4WejPobnvlz6dypJf_yI4PZ6DVuQKCgN3q7M_6CKDerufZYs8bpz05n8gHYiHFh9ODlO6yvKfuQy0Y_8MVhEbIS1_U2PxsQKTTK8aRUyLuJeVwrwoJ_aUTD9v-zElb4gKsqVj-MCeNTKMT0torRETztrt3PrHo-rnDiuCnqGEsz8kFDIoomqfLBvg07Eo7tyjKvoueFfYBsQuBT6jRWkTBPR_6s4zdBJOkYYmP7Y',
    totalPredictionsCount: 42,
    notLoseCount: 28,
    loseHalfCount: 4,
    loseCount: 6,
    loseDoubleCount: 4,
    totalPenaltyVnd: 45000, // Rank 4: 4.5 Penalty / 45,000 VND
  },
  {
    id: 'trunghieu',
    name: 'Trung Hiếu',
    avatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCDdhtlY4KTfgPxWjN3hS4yG3XpZzgF0WH1mryAHQLNcFTw6KmFTUptMoKVmm08e7-rDCeNkOJZfVK7VaEX9i1qk2HEDAgxZMbMTfKelrzZT_9fTTA5xPj6xzMeiATUeHuzmRgEIWRvn1Tbg9dM4ephW4-bcWQXDwNVijwbBK4RNDtlGqNozEGGfPQFDeLWLDmbC1bo-5uOPf9b6U7KcXQo75qwLt9Wf3wkSDkiVJkei3FrOQEcdxY9Lx2mB3EE6FRi7xJyrqJ7uqIk',
    totalPredictionsCount: 45,
    notLoseCount: 25,
    loseHalfCount: 5,
    loseCount: 10,
    loseDoubleCount: 5,
    totalPenaltyVnd: 60000, // Rank 5: 6.0 Penalty / 60,000 VND
  },
  {
    id: 'tunglam',
    name: 'Tùng Lâm',
    avatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDeriWM6go8xwuwH_Sm6g-aHWX2uB0qOv7ayCDLQ1xppHIqgpJ_3PBrvcgyTvbUsQjtwz6Hc_hDVdXUOwtxds4cNxYiqRGxRoczuqhiYp3BK763rXkOqklz1QfFzwVOGJtAorlLPpIuuiEMUs0D913qk-QSHmBzFGPgF1mgLbf7L9xbCrvpZAPqZuE0efKoYIPZe1aFZ6AEEybq1SVOA9Fez7yoJhsBIGL2fUHlWP6iqkoVPonEj35Yi5-Fvw4GnKHyEE2P-uqvBFAf',
    totalPredictionsCount: 38,
    notLoseCount: 20,
    loseHalfCount: 3,
    loseCount: 12,
    loseDoubleCount: 3,
    totalPenaltyVnd: 75000, // Rank 6: 7.5 Penalty / 75,000 VND
  },
  {
    id: 'tiendung',
    name: 'Tiến Dũng',
    avatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCS1mH4fvX7TIHkZftDiSctCGxJ8uiMA5M1nUw2SZU09fu85RbKgXQZ9VuwFPlH4S1Eb8MkahOEb5EdRw2UbP6PJ1CKhAxW3ZKK3BcwGwyfYEQAOsnRUOYitRjPj_c6dvUrVwbySTzU9GmTHfd9FWS7Ga0SD7j7GxSHtOBH5lWgqqOvcyQluH8tr8xdYvSI96Fd4CZ5DeiB2acPrnA9a4CUPCNrq_WoEFeq09E7hTEmNesF6vCv3cj8gxXaINPCW_S-ITkEcn0peyaN',
    totalPredictionsCount: 40,
    notLoseCount: 18,
    loseHalfCount: 2,
    loseCount: 15,
    loseDoubleCount: 5,
    totalPenaltyVnd: 80000, // Rank 7: 8.0 Penalty / 80,000 VND
  },
  {
    id: 'minhphuong',
    name: 'Minh Phương',
    avatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDpqtiZIkIKcx4PDf3lAFD2PdZtvpMfE2IXNEhVXIIjgnJkJHhqutcIMRtWqpj5nkbWijRGFBzRvfnL9s6Ww97AUZFGppEDeK54-_49Hmm6mhSrm6nDUeIV9WlefZ4n7u0C4QoG98H8tE0IcbeV0fa843S0Fssaed5y7kN59pR9EyL-FQ_qpO3yHM61gYVYH-qmnUCqsOIIJGZTPwjr2CSuBEUxGpLqtm-koBQMTSJyQan8b8E0kWCYRsoJl2UPxskRcCeLdpdoIY0x',
    totalPredictionsCount: 44,
    notLoseCount: 15,
    loseHalfCount: 10,
    loseCount: 15,
    loseDoubleCount: 4,
    totalPenaltyVnd: 125000, // Rank 8: 12.5 Penalty / 125,000 VND
  },
  {
    id: 'huy',
    name: 'Huy',
    avatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBKc3zbGFzQs3JKedCQzJn_2MXz5WXSJg47EXyzQRFmPzkFdPXWd3ThEst9n_hkbevpo6QV_qd6xLCO938h3hIt-8OVm-0o2vsqLnkXtMCbFBg5MkyoFTQwuTSTbljQKAP2ZQJHmal0aC7r3VtdRmmlVi3IhPNOlc2aX9yW-WAD1eYGrEbnCO_P10-t8cHxMDbsCQY-b_YOwdxMEjzOMfw1TB9r1i6cvOq_nzWbQNqAK-cGBXBVBFERHZoYi6gOgs8X9g8jfwUywf6O',
    totalPredictionsCount: 12,
    notLoseCount: 8,
    loseHalfCount: 1,
    loseCount: 2,
    loseDoubleCount: 1,
    totalPenaltyVnd: 15000, // #3 Rank custom status for Huy / 15,000 VND
  },
  {
    id: 'quynh',
    name: 'Quynh Le',
    avatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBR-1pQcXcwv7HiDGfHs4U3081CaCX6CcgKt_PcMSFNC4vonw92TyboollXAp41BchXI5gx4avqdpJJ8hrezlZv4YaTxXHYupDIrGiNhcF8aTC_prGVLqeaogvaV_KPsfC9S8VGc5DLYMqnU7SvR12zUMQnEntrgPFO7UCstNAcmt6WHBbXHvyBNuNbVQtRjZnPHv5KB8W-C5_y7Rb1HGolyAOpfvU9AHXk4XM3nf8BHJVQeirSJXLJ2gyfuklBiYU1Vy0dLa1BUhFK',
    totalPredictionsCount: 24,
    notLoseCount: 18,
    loseHalfCount: 1,
    loseCount: 4,
    loseDoubleCount: 1,
    totalPenaltyVnd: 5000, // 5,000 VND
  },
];

export const INITIAL_MATCHES: Match[] = [
  {
    id: 'm1',
    league: 'PREMIER LEAGUE',
    homeTeam: 'Man City',
    awayTeam: 'Liverpool',
    homeLogo: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCK4VaY9QgP8_9Iv1a66EUEFuLLSI98JtXpmf1UxZaqoShC6TFTASU0GJRUCY9BEqTXOwf8OtS4KLVJvkYcvmNTTIlC54CmOzB75K889uEGEIwfaZJA3i0ZA-FQ7r5WzU6fakrL8zA6RLyQmCe4rSsZcTEIi9v74SbXfL-p1f-44UJY1LP2_IfG83K2OcejiaUpSe5RU6B6bcuWT2eBw19vEA0AlodFJDUn_M2scln1PFhWpZAxtBq1KuKejZaFO28hqaz3ZLIaZKrz',
    awayLogo: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBI2lXJIn7__mb3PgO7QwQd-pmDW8zPzDMJ6reklxs6rbkOd-bSPej3CnQit2rNuROkFTd5VhrBafY-iEnWXJBbw3lDH7mieK4zSXih-Pg5LnEPl6QY5VmrbMCO8hMDdomnVEaSsN8T4OC4_GB_0i3JzFIIPV9I4YLu-P03zeoUQiI6reSyYnXXv6QFu6YeeSOiuXbsn_CuTnNU5ffXK9piddC01HB3BCysJNcJXCJjh0C3zIeM41yfdMW5_gfGNl-TxC301UiDWbKs',
    handicap: -0.75,
    time: '22:00',
    date: '20 Oct, 2024',
    stadium: 'Estadio San Mames',
    status: 'UPCOMING',
    isHot: true,
  },
  {
    id: 'm2',
    league: 'LA LIGA',
    homeTeam: 'Real Madrid',
    awayTeam: 'Barcelona',
    homeLogo: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAqyO-raHFNJXW0dPxDesISCSIG-GwcCnoiVY_Li6HoESgpsn3iOB6v7gCLSwtKEBzEpbSNSh4sZg2OffzdyhG4shUq3lNETYaVMVVdKFAbZkbODfCMP2ZOj-U309oCPc0woxpxEg5t_2VuhwXCbJBjzBsp-VaJm21cpbD2F6qvk52Iouuz5jYNyDn8uo3uayIWZLCZNf-61eSVr3xNxXOIdjCXI-0857z_bAl0ES3dophMYaFx6QFRrhm5BbXdAV9fmL0AMpJeeGGU',
    awayLogo: 'https://lh3.googleusercontent.com/aida-public/AB6AXuD_BLCbi6O0RS90V7-cQ91z8HgCDdh2KulFDVgnOCfPwWucgwWNF9Nec-YpgRGxDDVho_ib-uvRlUMH7Pe6Xu8jt2QtAG-SJg4rrcyQHN94tLGUcL-te5enT-wAyvZX_22_oQF7xDg1efkZDixZWHuMttsklcZJwTVjnvRhVnv3IQBgz1vyhteYPyOoMfu3fZMeG8GP6cYrgqtseXK7AwdZYOiZizQ94ZpcvswQCSEqH8IedtCoUe511Fm2GFq7DbDsbLG3aNkS03Zy',
    handicap: -0.25,
    time: 'LOCKED',
    date: '25 Oct, 2024',
    stadium: 'Santiago Bernabéu',
    status: 'FINISHED',
    homeGoals: 1,
    awayGoals: 3,
  },
  {
    id: 'm3',
    league: 'CHAMPIONS LEAGUE',
    homeTeam: 'Bayern',
    awayTeam: 'PSG',
    homeLogo: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBUK0n4FmbP_17Vd2Y87Hhh_o5OvQbCmjQT2GnmJFCsjMo79iJLFAyYKRe9jGPhsjVSWZBpTdUSw4m72xnPFAC8Tum9THCBP-naoZ9IIcGlPQxFefGp5-3G2a9LTf0r0s_xQbi7zNgv67WCfbDZ28iS0j7LukAA1TxxGtkoyjsUVIvRRsVBM5r9L6IlO27l-gXs2QYqoR2aKhUY6Qsteba5VgzgTOxchWhxN223Vcqf7mZzNyLX_SnSjRkQDORflrQWZQVO3d7cqENf',
    awayLogo: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDnQbnm_cFdr6DOPEtKMJZNKFECiS1V-68N8SjCVk6luGB2z2mmmb2LKc5OkOFCxJUnyswnshlzrFDTSo8nTvnFg14JJxOjyiPOkzVutnNjN7BFF1q-AEj4dKqgOiBQBXbYRYcTuDhxQm0FJBrmzVQIX0tOrWmDJHVKzorR_4R1mMh6ISNxJOyf4lTYDvLssuX_ipd5g-odHYHiIiAnAp2DzBA2rcoqghc4Iv-d0eIGCmYzuM5qOSv1PEFW8L2_nXSix8FrX4AUALvd',
    handicap: 0.0,
    time: '20:15',
    date: '28 Oct, 2024',
    stadium: 'Allianz Arena',
    status: 'LIVE',
    homeGoals: 2,
    awayGoals: 1,
    liveTimeText: "67'",
  },
  {
    id: 'm4',
    league: 'SERIE A',
    homeTeam: 'Juventus',
    awayTeam: 'Inter Milan',
    homeLogo: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCm3ZKAuwLaDGO6sUlM5AXg2osk0cz9BtfwF3T1_9Nx94FdC1PlhYadq3sBkK77yGZWGJl0EkuC8b60O3EJHPwvFhiNnzlQvzNLG4kdeC4xCsHg5v3pcuadIvfNIuSqJw32FgZYxSWPssm8TtB-GQUSfJGN_gAuBqxmcOllPym4ZXfENzUicL7xbG_g-9nrtlhx6urxht7YOd6ZMAFF5hr4tTP8zkzJ5U3aq6ltFv0LibaNRezCaunZYOHypZl_Ls5f0WDoDD-xC5Xy',
    awayLogo: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBmjSQCzMMjVJcUqHeRoR7fljP8VkXG3rPUw4ik3teYjYume-L27YxOZMJfmvGnJ5uU88PR5gGRVgsepZCFgWLPApsBUAOq3-2SonQWB2KoVrJFr2CZ7Qh2E5eqo7pxmiNLZKPn2LS8kH1MRTdUUwgCU9n8_YJrrAvUCrJCdNcOW0UWXOS4UmPFlZMgqimdotmJA3MKTO62PiVW36xVkgaHU9ex8TGKu7RNV-8DJmhsXGwnCeMLIffllmwKj6zOKKZRumbSyirV0sCx',
    handicap: 0.5,
    time: '01:45',
    date: '30 Oct, 2024',
    stadium: 'Alliance Stadium',
    status: 'UPCOMING',
  },
  {
    id: 'm5',
    league: 'PREMIER LEAGUE',
    homeTeam: 'Liverpool',
    awayTeam: 'Chelsea',
    homeLogo: 'https://lh3.googleusercontent.com/aida-public/AB6AXuADnpYEzLMY0XtHf_9SOU7CDWtTSVCno2ZpC8n_RwHMzDyTwZGWf8VpttBnnM4qBbkjYh3WHaXu9l__f-l3khNW6ptVcXGIhwi12-mB-KjtCY2leyaOls4EhgMZDf5HNGm5HOkJn9i2PQuaqKFcsVfB7YlCgyENCa2MB9efRsscpqwh5-ouGg-rwZV0HIMDH6ETMnf8PjCYK2eFl3bvpXVH53GDHDCmUAXydww8E_ywZ1E_iAGlQQNVeZKtqP_DBdbtDb4QH5I7f68I',
    awayLogo: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAx38xXrLE8qeGoYy6IiH-9yICR-2hwpAvMRfMataKOrgKnQ2rDrixBu0FXYcOK5KVABbg7cJM18q6E_yKTnrGDEBNsCdqF2jxQxOem-jYM2Krl9do168m9u5iiyTvB5pwft1JktsDD23kLiRXkCAT-LGnyZNmmcmRliRS9CDK89mKmJsQuFXwVRAuiouDLpZvfFizwlhn5SGgkVwkvvsCR7DmddRXNRi8dwFwoADLFzvVfQLJTkn7nK7sT7UySTbh5r-oE8aWk1S4h',
    handicap: -0.5,
    time: 'FINISHED',
    date: '20 Oct, 2024',
    stadium: 'Anfield, Liverpool',
    status: 'FINISHED',
    homeGoals: 2,
    awayGoals: 1,
  },
];

export const INITIAL_PREDICTIONS: Prediction[] = [
  // For Match 1 (Man City vs Liverpool) handicap -0.75
  { matchId: 'm1', playerId: 'huy', choice: 'HOME', timestamp: '1 hour ago' },
  { matchId: 'm1', playerId: 'alex', choice: 'AWAY', timestamp: '34 mins ago' },
  { matchId: 'm1', playerId: 'quynh', choice: 'HOME', timestamp: '2 hours ago' },
  { matchId: 'm1', playerId: 'anhquoc', choice: 'HOME', timestamp: '45 mins ago' },

  // For Match 3 (Bayern vs PSG) handicap 0.0
  { matchId: 'm3', playerId: 'huy', choice: 'HOME', timestamp: 'Just now' },
  { matchId: 'm3', playerId: 'quynh', choice: 'AWAY', timestamp: '1 hour ago' },
  { matchId: 'm3', playerId: 'anhquoc', choice: 'HOME', timestamp: '3 hours ago' },

  // For Match 5 (Liverpool vs Chelsea) finished 2-1, handicap -0.5
  { matchId: 'm5', playerId: 'huy', choice: 'HOME', timestamp: 'Finished' },
  { matchId: 'm5', playerId: 'alex', choice: 'HOME', timestamp: 'Finished' },
  { matchId: 'm5', playerId: 'quynh', choice: 'AWAY', timestamp: 'Finished' },
  { matchId: 'm5', playerId: 'anhquoc', choice: 'HOME', timestamp: 'Finished' },
];

export const INITIAL_FEED: ActivityFeedItem[] = [
  {
    id: 'f1',
    playerName: 'Minh',
    actionText: 'changed prediction to',
    targetText: 'Arsenal',
    type: 'change_prediction',
    timeAgo: '2 MINS AGO',
  },
  {
    id: 'f2',
    playerName: 'DN',
    actionText: 'received',
    targetText: 'lose_double',
    type: 'penalty',
    statusType: 'LOSE_DOUBLE',
    timeAgo: '15 MINS AGO',
  },
  {
    id: 'f3',
    playerName: 'Quynh Le',
    actionText: 'joined the prediction for',
    targetText: 'Liverpool vs Spurs',
    type: 'join_prediction',
    timeAgo: '1 HOUR AGO',
  },
];
